# Generated by Django 6.1 on 2026-08-28 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telegram_id', models.CharField(blank=True, max_length=33, validators=[django.core.validators.RegexValidator(message='Enter a valid Telegram username (for example, @username).', regex='^@?[A-Za-z0-9_]{5,32}$')])),
                ('phone', models.CharField(blank=True, max_length=26, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9][0-9\\s().-]{6,24}$')])),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=5000)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('email', ''), _negated=True), models.Q(('telegram_id', ''), _negated=True), models.Q(('phone', ''), _negated=True), _connector='OR'), name='contact_message_has_contact_method', violation_error_message='At least one contact method is required: email, Telegram ID, or phone.')],
            },
        ),
    ]
