# Generated by Django 6.1 on 2026-08-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['display_order', 'title']},
        ),
        migrations.AddField(
            model_name='skill',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
