# Generated by Django 6.1 on 2026-08-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_skill_options_skill_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fa_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fa_short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='fa_title',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
