# Generated by Django 6.1 on 2026-08-28 18:17

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                storage=accounts.models.resume_storage,
                upload_to="resume/",
            ),
        ),
    ]
