# Generated by Django 6.1 on 2026-08-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fa_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fa_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fa_short_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
